#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
step_7g_plotheatmap_clustering.py - Generate clustered heatmaps for H3K27me3 DMSO peaks.

Mirrors step_8c_plotheatmap_clustering.py, clustering over matrices generated by step_7e
(base_prefix = 'k27me3_dmso_peaks'). Clusters based on H3K27me3 DMSO and 1uM signals (columns 3 and 4).
"""

import os
import time
import argparse
import config

### Configuration
regions_file = os.path.join(
    config.PEAKDIR, "csaw",
    "H3K27me3_DMSO.w150.d50.filt3.w2000.d500.filt1.5.lfc1.merge100.tmm.bed"
)
avg_summary_plot = "mean"
base_prefix = "k27me3_dmso_peaks"

WINDOW_CONFIGS = [
    (10000, 10000),
    (5000, 5000),
    (2000, 2000),   # +/- 2 kb
]

plot_type = "se"
color_maps = []
color_list = [
    "'white,#8c96c6'", "'white,#8c96c6'",
    "'white,#8c6bb1'", "'white,#8c6bb1'",
    "'white,#58135e'", "'white,#58135e'",
    "'white,#39107b'", "'white,#39107b'"
]
min_intensity = "0 0 0 0 0 0 0 0"
max_intensity = "40 40 30 30 4 4 4 4"
plot_height = 12
plot_width = 3.5
what_to_show = "plot, heatmap and colorbar"
x_label = "distance (bp)"
y_label = "signal"
ref_point_label = "'peak\ncenter'"
sample_labels = [
    "'H3K27me2\nDMSO'", "'H3K27me2\n1uM'",
    "'H3K27me3\nDMSO'", "'H3K27me3\n1uM'", 
    "'CBX2\nDMSO'", "'CBX2\n1uM'",
    "'EZH2\nDMSO'", "'EZH2\n1uM'"
]
regions_labels = None  # e.g., ["'Cluster 1'", "'Cluster 2'"] (--regionsLabel / -z)
cluster_using = "3 4"  # cluster on H3K27me3 DMSO and 1uM signals only
sort_using_samples = "3 4"  # sort by H3K27me3 signal
plot_title = None
y_min = "0 0 0 0 0 0 0 0"
y_max = "40 40 30 30 4 4 4 4"
legend_location = "best"
per_group = False
image_format = "svg"
###

def run_plot_heatmap(upstream_region: int, downstream_region: int, use_hclust: bool, n_clust: int):
    """
    Creates and submits a batch script for plotHeatmap operations
    for a single (upstream, downstream) window around the reference point.
    """
    cluster_algo = "hclust" if use_hclust else "kmeans"
    clustering_param = f"--{cluster_algo}"

    half_kb = upstream_region // 1000

    output_suffix = f"{half_kb}kb_{cluster_algo}"
    if n_clust is not None:
        output_suffix += f"_{n_clust}"

    matrix_file = f"{base_prefix}_{half_kb}kb.gz"

    work_dir = config.DEEPTOOLSDIR
    matrix_dir = os.path.join(work_dir, "matrix")
    plot_dir = os.path.join(work_dir, "plots")
    regions_dir = os.path.join(work_dir, "regions")

    output_prefix = f"{base_prefix}_{output_suffix}"
    matrix_path = os.path.join(matrix_dir, matrix_file)

    optional_param = []
    if color_maps: optional_param.append(f"--colorMap {' '.join(color_maps)}")
    if color_list: optional_param.append(f"--colorList {' '.join(color_list)}")
    if sample_labels: optional_param.append(f'--samplesLabel {" ".join(sample_labels)}')
    if regions_labels: optional_param.append(f'--regionsLabel {" ".join(regions_labels)}')
    if min_intensity and "auto" not in min_intensity: optional_param.append(f"--zMin {min_intensity}")
    if max_intensity and "auto" not in max_intensity: optional_param.append(f"--zMax {max_intensity}")
    if x_label: optional_param.append(f"-x '{x_label}'")
    if y_label: optional_param.append(f"-y '{y_label}'")
    if y_min and "auto" not in y_min: optional_param.append(f"--yMin {y_min}")
    if y_max and "auto" not in y_max: optional_param.append(f"--yMax {y_max}")
    if per_group: optional_param.append("--perGroup")
    if plot_title: optional_param.append(f"--plotTitle '{plot_title}'")

    optional_param.append(f"--clusterUsingSamples {cluster_using}")

    if sort_using_samples is not None:
        optional_param.append(f"--sortUsingSamples {sort_using_samples}")

    optional_params = " \\\n  ".join(optional_param)

    heatmap_file = os.path.join(plot_dir, f"{output_prefix}.svg")
    profile_file = os.path.join(plot_dir, f"{output_prefix}_profile.svg")
    output_regions = os.path.join(plot_dir, f"{output_prefix}_regions")

    job_name = f"{output_prefix}_plotHeatmap"
    log_dir = os.path.join(plot_dir, "log")
    log_out = os.path.join(log_dir, f"{output_prefix}_heatmap.log")
    log_err = os.path.join(log_dir, f"{output_prefix}_heatmap.error")
    batch_file = os.path.join(log_dir, f"{output_prefix}_heatmap.batch")

    os.makedirs(work_dir, exist_ok=True)
    os.makedirs(matrix_dir, exist_ok=True)
    os.makedirs(plot_dir, exist_ok=True)
    os.makedirs(regions_dir, exist_ok=True)
    os.makedirs(log_dir, exist_ok=True)

    if n_clust is not None:
        cluster_bash_logic = f"best_k={n_clust}\n"
    else:
        cluster_bash_logic = f"""
SENTINEL="{plot_dir}/{output_prefix}_best_k.txt"
if [ -f "$SENTINEL" ]; then
   best_k=$(cat "$SENTINEL")
   echo "Reusing cached optimal k=$best_k"
else
   best_k=2
   best_score="-1000"

   for k in {{2..4}}; do
      echo "Evaluating k=$k"
      plotHeatmap -m {matrix_path} \\
         -o {plot_dir}/{output_prefix}_k${{k}}.svg \\
         {clustering_param} $k \\
         --outFileSortedRegions {regions_dir}/{output_prefix}_k${{k}}.bed \\
         --silhouette \\
         --plotType '{plot_type}' \\
         --averageTypeSummaryPlot '{avg_summary_plot}' \\
         --refPointLabel {ref_point_label} \\
         --whatToShow '{what_to_show}' \\
         --heatmapHeight {plot_height} \\
         --heatmapWidth {plot_width} \\
         {optional_params} \\
         --legendLocation {legend_location} \\
         --plotFileFormat {image_format}

      score=$(awk 'BEGIN{{FS="\\t"; sum=0; count=0}} /^[^#]/ {{sum+=$NF; count++}} END{{if(count>0) print sum/count; else print "-1000"}}' {regions_dir}/{output_prefix}_k${{k}}.bed)
      echo "Score for k=$k is $score"

      is_greater=$(awk -v s1="$score" -v s2="$best_score" 'BEGIN{{if(s1+0 > s2+0) print "1"; else print "0"}}')
      if [ "$is_greater" -eq 1 ]; then
         best_score=$score
         best_k=$k
      fi
   done
   echo "Optimal clusters k=$best_k with score $best_score"
   echo "$best_k" > "$SENTINEL"
fi
"""

    batch_cmd = f"""\
#!/bin/bash
#BSUB -P {config.PROJECT_NAME}
#BSUB -J {job_name}
#BSUB -oo {log_out}
#BSUB -eo {log_err}
#BSUB -q {config.BSUB_QUEUE}
#BSUB -n 8
#BSUB -M 65536
#BSUB -R "rusage [mem=8192] span[hosts=1]"

source {config.HOMEDIR}/miniconda3/etc/profile.d/conda.sh
conda activate chipseq

{cluster_bash_logic}

plotHeatmap -m {matrix_path} \\
   -o {heatmap_file} \\
   {clustering_param} $best_k \\
   --outFileSortedRegions {regions_dir}/{output_prefix}.bed \\
   --plotType '{plot_type}' \\
   --averageTypeSummaryPlot '{avg_summary_plot}' \\
   --refPointLabel {ref_point_label} \\
   --whatToShow '{what_to_show}' \\
   --heatmapHeight {plot_height} \\
   --heatmapWidth {plot_width} \\
   {optional_params} \\
   --legendLocation {legend_location} \\
   --plotFileFormat {image_format}

# Extract clusters into separate region BED files dynamically
if [ -n "$best_k" ]; then
    for c in $(seq 1 $best_k); do
        cluster_name="cluster_${{c}}"
        cluster_bed="{regions_dir}/{output_prefix}_cluster_${{c}}_coords.bed"
        cluster_ids="{regions_dir}/{output_prefix}_cluster_${{c}}_ids.txt"
        final_cluster="{regions_dir}/{output_prefix}_cluster_${{c}}.bed"
        
        awk -v clus="$cluster_name" 'BEGIN{{FS=OFS="\\t"}} !/^#/ && $NF==clus' {regions_dir}/{output_prefix}.bed > "$cluster_bed"
        awk '{{print $4}}' "$cluster_bed" > "$cluster_ids"
        grep -Fwf "$cluster_ids" {regions_file} > "$final_cluster" 2>/dev/null || true
        
        # If grep matched nothing (e.g., input regions file only has 3 columns and column 4 was synthesized as chr:start-end),
        # extract the coordinates directly from plotHeatmap sorted regions output:
        if [ ! -s "$final_cluster" ] && [ -s "$cluster_bed" ]; then
            awk 'BEGIN{{FS=OFS="\\t"}} {{print $1, $2, $3}}' "$cluster_bed" > "$final_cluster"
        fi
        rm -f "$cluster_bed" "$cluster_ids"
    done
fi

# Print resource usage at the end of the job
echo "=== Resource usage summary ==="
bjobs -l $LSB_JOBID | grep -A10 "Resource usage"
"""

    with open(batch_file, 'w', encoding='utf-8') as f:
        f.write(batch_cmd)

    print(f"Submitting {job_name}")
    os.system(f"bsub < {batch_file}")
    time.sleep(1)

def main():
    """
    Main workflow controller — submits one job per window config
    """
    parser = argparse.ArgumentParser(description="Generate clustered heatmaps for H3K27me3 DMSO peaks")
    parser.add_argument("--hclust", action="store_true", help="Use hclust instead of kmeans")
    parser.add_argument("--n_clust", type=int, default=None, help="Force N clusters instead of calculating optimal")
    parser.add_argument("--base_prefix", type=str, help="Overwrite base_prefix")
    parser.add_argument("--avg_summary", type=str, help="Overwrite avg_summary_plot")
    parser.add_argument("--regions", type=str, help="Overwrite regions_file")
    parser.add_argument("--min_intensity", type=str, help="Overwrite min_intensity")
    parser.add_argument("--max_intensity", type=str, help="Overwrite max_intensity")
    parser.add_argument("--ymin", type=str, help="Overwrite y_min")
    parser.add_argument("--ymax", type=str, help="Overwrite y_max")
    parser.add_argument("--x_label", type=str, help="Overwrite x_label")
    parser.add_argument("--y_label", type=str, help="Overwrite y_label")
    parser.add_argument("--cluster_using", type=str, help="Overwrite cluster_using")
    parser.add_argument("--regions_label", type=str, nargs="+", help="Custom labels for clusters/regions displayed on the heatmap (--regionsLabel / -z)")
    args = parser.parse_args()

    global base_prefix, avg_summary_plot, regions_file, min_intensity, max_intensity, y_min, y_max, x_label, y_label, cluster_using, regions_labels

    if args.avg_summary:
        avg_summary_plot = args.avg_summary

    if args.base_prefix:
        base_prefix = args.base_prefix
    elif args.avg_summary:
        base_prefix = "k27me3_dmso_peaks"

    if args.regions: regions_file = args.regions
    if args.min_intensity: min_intensity = args.min_intensity
    if args.max_intensity: max_intensity = args.max_intensity
    if args.ymin: y_min = args.ymin
    if args.ymax: y_max = args.ymax
    if args.x_label: x_label = args.x_label
    if args.y_label: y_label = args.y_label
    if args.cluster_using: cluster_using = args.cluster_using
    if args.regions_label: regions_labels = args.regions_label

    print(f"Using regions: {regions_file}")
    print(f"Average summary plot: {avg_summary_plot}")
    print(f"Base prefix: {base_prefix}")
    print(f"Clustering: {'hclust' if args.hclust else 'kmeans'} (n={args.n_clust if args.n_clust else 'auto'})")

    for upstream, downstream in WINDOW_CONFIGS:
        run_plot_heatmap(upstream, downstream, args.hclust, args.n_clust)

if __name__ == "__main__":
    main()
